"""add_onboarded_by_to_employees

Revision ID: 363e2fb351a8
Revises: 
Create Date: 2026-03-20 13:39:58.032638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363e2fb351a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('onboarded_by', sa.UUID(), nullable=True))
    op.add_column('employees', sa.Column('onboarded_by_email', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'employees', 'employees', ['onboarded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'onboarded_by_email')
    op.drop_column('employees', 'onboarded_by')
    # ### end Alembic commands ###
