"""Add tan_number

Revision ID: 4e9c552f4dc2
Revises: 2971868b41a6
Create Date: 2026-04-24 16:04:28.822351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9c552f4dc2'
down_revision: Union[str, None] = '2971868b41a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('tan_number', sa.String(length=20), nullable=True))
    op.alter_column('employees', 'uan_number',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'uan_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_column('employees', 'tan_number')
    # ### end Alembic commands ###
