"""insurance fix

Revision ID: b86daab36540
Revises: aa67feb120af
Create Date: 2026-03-25 12:56:25.429635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86daab36540'
down_revision: Union[str, None] = 'aa67feb120af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance_info', sa.Column('submitted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('insurance_info', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insurance_info', 'submitted_at')
    op.drop_column('insurance_info', 'submitted')
    # ### end Alembic commands ###
