"""add_employee_salary_and_pan_number

Revision ID: dda6019d046b
Revises: 7a2c9f1d3e8b
Create Date: 2026-04-15 16:59:57.925672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda6019d046b'
down_revision: Union[str, None] = '7a2c9f1d3e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('pan_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'pan_number')
    # ### end Alembic commands ###
