"""insurance_docs_roles_update

Revision ID: fc21dd68b5ff
Revises: b86daab36540
Create Date: 2026-03-30 13:04:30.817391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc21dd68b5ff'
down_revision: Union[str, None] = 'b86daab36540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance_info', sa.Column('smoking_status', sa.String(length=20), nullable=True))
    op.add_column('insurance_info', sa.Column('spouse_name', sa.String(length=200), nullable=True))
    op.add_column('insurance_info', sa.Column('spouse_dob', sa.Date(), nullable=True))
    op.add_column('insurance_info', sa.Column('spouse_gender', sa.String(length=20), nullable=True))
    op.add_column('insurance_info', sa.Column('children', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insurance_info', 'children')
    op.drop_column('insurance_info', 'spouse_gender')
    op.drop_column('insurance_info', 'spouse_dob')
    op.drop_column('insurance_info', 'spouse_name')
    op.drop_column('insurance_info', 'smoking_status')
    # ### end Alembic commands ###
